services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: raul
      POSTGRES_PASSWORD: 1234

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  postgres_data:


